"""empty message

Revision ID: ca0d04fabb6c
Revises: 3deecaaf5205
Create Date: 2026-02-16 18:37:50.173052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0d04fabb6c'
down_revision = '3deecaaf5205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocklist',
    sa.Column('jti', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocklist')
    # ### end Alembic commands ###
